### ISSUE TITLE
about QCA on Windows

### ISSUE THREAD

**Issue by librehat** [JPNaude/dev_notes#1]
Hi, I read your notes about compiling QCA on Windows.

Did you try to use `libqca` in a project? Because I built it successfully with MinGW toolchain, but I can't use it in any project. Always undefined reference errors. Just want to make sure whether it's my problem.

**Comment by JPNaude** [comment]
Hi, its been in used on Linux (Centos 4,5 + Ubuntu) and Windows 7,8.
I've used MSVC though, so not sure if its MinGW?
Are you able to try with MSVC?

**Comment by librehat** [comment]
Thank you for your reply.

Yes, I tried MSVC later. It seems QCA can't be compiled as static lib. It'll fail on both Linux and Windows, both MSVC and MinGW.

Seems it can only be built as shared lib.

**Comment by JPNaude** [comment]
Oh ok, glad you got it figured out. That's good to know.
Will close this ticket for now.
